/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const PriceStat = IDL.Record({
  'year' : IDL.Nat,
  'price' : IDL.Float64,
});
export const PredictionResult = IDL.Record({
  'estimatedPrice' : IDL.Float64,
  'keyStatsCount' : IDL.Nat,
  'priceHistory' : IDL.Vec(PriceStat),
  'priceRangeHigh' : IDL.Float64,
  'marketDemand' : IDL.Float64,
  'confidence' : IDL.Float64,
  'priceRangeLow' : IDL.Float64,
  'compsAveragePrice' : IDL.Float64,
});
export const HouseFeatures = IDL.Record({
  'lotSizeSqft' : IDL.Float64,
  'hasPool' : IDL.Bool,
  'propertyType' : IDL.Text,
  'bedrooms' : IDL.Float64,
  'zipCode' : IDL.Text,
  'hasGarage' : IDL.Bool,
  'hasFireplace' : IDL.Bool,
  'bathrooms' : IDL.Float64,
  'sizeSqft' : IDL.Float64,
  'yearBuilt' : IDL.Float64,
  'recentlyRenovated' : IDL.Bool,
});
export const PredictionEntry = IDL.Record({
  'result' : PredictionResult,
  'features' : HouseFeatures,
  'timestamp' : IDL.Int,
});
export const ComparableProperty = IDL.Record({
  'bedrooms' : IDL.Float64,
  'size' : IDL.Float64,
  'address' : IDL.Text,
  'bathrooms' : IDL.Float64,
  'price' : IDL.Float64,
});

export const idlService = IDL.Service({
  'getAllPredictions' : IDL.Func([], [IDL.Vec(PredictionEntry)], ['query']),
  'getComparableProperties' : IDL.Func(
      [IDL.Text, IDL.Float64],
      [IDL.Vec(ComparableProperty)],
      ['query'],
    ),
  'getPrediction' : IDL.Func([IDL.Text], [PredictionResult], ['query']),
  'predictPrice' : IDL.Func([HouseFeatures], [PredictionResult], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const PriceStat = IDL.Record({ 'year' : IDL.Nat, 'price' : IDL.Float64 });
  const PredictionResult = IDL.Record({
    'estimatedPrice' : IDL.Float64,
    'keyStatsCount' : IDL.Nat,
    'priceHistory' : IDL.Vec(PriceStat),
    'priceRangeHigh' : IDL.Float64,
    'marketDemand' : IDL.Float64,
    'confidence' : IDL.Float64,
    'priceRangeLow' : IDL.Float64,
    'compsAveragePrice' : IDL.Float64,
  });
  const HouseFeatures = IDL.Record({
    'lotSizeSqft' : IDL.Float64,
    'hasPool' : IDL.Bool,
    'propertyType' : IDL.Text,
    'bedrooms' : IDL.Float64,
    'zipCode' : IDL.Text,
    'hasGarage' : IDL.Bool,
    'hasFireplace' : IDL.Bool,
    'bathrooms' : IDL.Float64,
    'sizeSqft' : IDL.Float64,
    'yearBuilt' : IDL.Float64,
    'recentlyRenovated' : IDL.Bool,
  });
  const PredictionEntry = IDL.Record({
    'result' : PredictionResult,
    'features' : HouseFeatures,
    'timestamp' : IDL.Int,
  });
  const ComparableProperty = IDL.Record({
    'bedrooms' : IDL.Float64,
    'size' : IDL.Float64,
    'address' : IDL.Text,
    'bathrooms' : IDL.Float64,
    'price' : IDL.Float64,
  });
  
  return IDL.Service({
    'getAllPredictions' : IDL.Func([], [IDL.Vec(PredictionEntry)], ['query']),
    'getComparableProperties' : IDL.Func(
        [IDL.Text, IDL.Float64],
        [IDL.Vec(ComparableProperty)],
        ['query'],
      ),
    'getPrediction' : IDL.Func([IDL.Text], [PredictionResult], ['query']),
    'predictPrice' : IDL.Func([HouseFeatures], [PredictionResult], []),
  });
};

export const init = ({ IDL }) => { return []; };