/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ComparableProperty {
  'bedrooms' : number,
  'size' : number,
  'address' : string,
  'bathrooms' : number,
  'price' : number,
}
export interface HouseFeatures {
  'lotSizeSqft' : number,
  'hasPool' : boolean,
  'propertyType' : string,
  'bedrooms' : number,
  'zipCode' : string,
  'hasGarage' : boolean,
  'hasFireplace' : boolean,
  'bathrooms' : number,
  'sizeSqft' : number,
  'yearBuilt' : number,
  'recentlyRenovated' : boolean,
}
export interface PredictionEntry {
  'result' : PredictionResult,
  'features' : HouseFeatures,
  'timestamp' : bigint,
}
export interface PredictionResult {
  'estimatedPrice' : number,
  'keyStatsCount' : bigint,
  'priceHistory' : Array<PriceStat>,
  'priceRangeHigh' : number,
  'marketDemand' : number,
  'confidence' : number,
  'priceRangeLow' : number,
  'compsAveragePrice' : number,
}
export interface PriceStat { 'year' : bigint, 'price' : number }
export interface _SERVICE {
  'getAllPredictions' : ActorMethod<[], Array<PredictionEntry>>,
  'getComparableProperties' : ActorMethod<
    [string, number],
    Array<ComparableProperty>
  >,
  'getPrediction' : ActorMethod<[string], PredictionResult>,
  'predictPrice' : ActorMethod<[HouseFeatures], PredictionResult>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];